### ISSUE TITLE
netcdfAll-5.5.3.jar Unable to release handle after reading file

### ISSUE THREAD

**Issue by breezePeak** [Unidata/netcdf-java#1258] opened 2023-11-09 04:39 UTC
### Versions impacted by the bug

netcdfAll-5.5.3.jar 

### What went wrong?

Please describe the bug.

### Relevant stack trace

```shell
try (NetcdfFile ncfile = NetcdfFiles.open(path)) {
// Do cool stuff here
} catch (IOException ioe) {
ioe.printStackTrace();
}
System.out.println("111111");
Break point on the last line，After starting debugging，Attempting to delete the read in file, Win11 shows that it cannot be deleted,Why is this
```

### If you have an example file that you can share, please attach it to this issue.
If so, may we include it in our test datasets to help ensure the bug does not return once fixed?
Note: the test datasets are publicly accessible without restriction.

Yes

### Code of Conduct

- [X] I agree to follow the UCAR/Unidata Code of Conduct

**Comment by tdrwenski** [comment] 2023-11-15 16:33
Duplicate of https://github.com/Unidata/netcdf-java/discussions/1257

**Closed as not planned by tdrwenski** 2023-11-15 16:33 UTC
Labels: bug
