### ISSUE TITLE
[5.5-SNAPSHOT]: WMS error: Coordinate values must increase or decrease monotonically

### ISSUE THREAD

**Issue by pedro-cf** [Unidata/netcdf-java#1201] opened 2023-06-15 16:07 UTC
### Versions impacted by the bug

v5.x, v6.x, v7.x

### What went wrong?

When accessing NETCDF via-WMS in TDS I'm getting this error in the logs:

```log
2023-06-15T15:02:46.751 +0000 [   1522855][     200] WARN  - uk.ac.rdg.resc.edal.dataset.cdm.NetcdfDatasetAggregator - Dataset /usr/local/tomcat/content/thredds/public/localdata/2019022300.nc is not in active dataset list but has been asked to be released!  This is not harmful in itself but may indicate a coding error whereby a dataset has been marked to be released from the cache multiple times.

2023-06-15T15:02:46.751 +0000 [   1522855][     200] WARN  - uk.ac.rdg.resc.edal.wms.WmsServlet - Wms Exception caught: "Problem creating dataset testAll/2019022300.nc" from:uk.ac.rdg.resc.edal.dataset.cdm.CdmDatasetFactory:133 Cause: Coordinate values must increase or decrease monotonically
```

and this error in the webpage ***http://localhost:8087/thredds/wms/testAll/wms_not_working_2023051700.nc?service=WMS&version=1.3.0&request=GetCapabilities***:

```xml
<ServiceExceptionReport xmlns="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.3.0" xsi:schemaLocation="http://www.opengis.net/ogc http://schemas.opengis.net/wms/1.3.0/exceptions_1_3_0.xsd">
<ServiceException> Problem creating dataset testAll/wms_not_working_2023051700.nc Cause: Coordinate values must increase or decrease monotonically </ServiceException>
</ServiceExceptionReport>
```

NETCDF in question: https://drive.google.com/file/d/1ypnvsHarmJxZgeueGXXSDw4yVNaSi_mO/view?usp=sharing

my catalog:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<catalog name="THREDDS Server Default Catalog : You must change this to fit your server!"
         xmlns="http://www.unidata.ucar.edu/namespaces/thredds/InvCatalog/v1.0"
         xmlns:xlink="http://www.w3.org/1999/xlink"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.unidata.ucar.edu/namespaces/thredds/InvCatalog/v1.0
           https://schemas.unidata.ucar.edu/thredds/InvCatalog.1.0.6.xsd">
  
  <service name="all" base="" serviceType="compound">
    <service name="odap" serviceType="OpenDAP" base="/thredds/dodsC/"/>
    <service name="dap4" serviceType="DAP4" base="/thredds/dap4/"/>
    <service name="http" serviceType="HTTPServer" base="/thredds/fileServer/"/>
    <service name="wcs" serviceType="WCS" base="/thredds/wcs/"/>
    <service name="wms" serviceType="WMS" base="/thredds/wms/"/>
    <service name="ncssGrid" serviceType="NetcdfSubset" base="/thredds/ncss/grid/"/>
    <service name="ncssPoint" serviceType="NetcdfSubset" base="/thredds/ncss/point/"/>
    <service name="cdmremote" serviceType="CdmRemote" base="/thredds/cdmremote/"/>
    <service name="iso" serviceType="ISO" base="/thredds/iso/"/>
    <service name="ncml" serviceType="NCML" base="/thredds/ncml/"/>
    <service name="uddc" serviceType="UDDC" base="/thredds/uddc/"/>
  </service>

  <dataset name="Catalogs" ID="Catalogs">
    <datasetScan name="Local Files" 
      ID="testDatasetScan"
      path="testAll"
      location="content/localdata">
      <metadata inherited="true">
        <serviceName>all</serviceName>
      </metadata>
    </datasetScan>
  </dataset>

</catalog>
```

### If you have an example file that you can share, please attach it to this issue.
If so, may we include it in our test datasets to help ensure the bug does not return once fixed?
Note: the test datasets are publicly accessible without restriction.

Yes

### Code of Conduct

- [X] I agree to follow the UCAR/Unidata Code of Conduct

**Comment by haileyajohnson** [comment] 2023-06-15 16:13
Duplicate of #1060

**Closed as completed by haileyajohnson** 2023-06-15 16:13 UTC
Labels: bug

**Comment by pedro-cf** [comment] 2023-06-15 16:18
> Duplicate of #1060

Is there any possible solution on my end? or any chance you could explain the problem ?

**Comment by haileyajohnson** [comment] 2023-06-15 16:28
There is no solution as of now but we're working on the problem. You can see a description of why it is occurring as well as updates on progress on the other issue.

**Comment by ethanrd** [comment] 2023-06-15 17:00
This is a netCDF-4 file rather than GRIB. So, while similar symptoms, I don't think this is a duplicate of #1060.

It looks like the `depth` variable isn't a legal "coordinate variable". To be a "coordinate variable", the variable must be strictly monotonic either increasing or decreasing. The `depth` array in this file starts with three values of `4600` (`ncdump -v depth wms_not_working_2023051700.nc`):

```
netcdf wms_not_working_2023051700 {
...
data:

 depth = **4600, 4600, 4600**, 4334.079, 3956.516, 3577.858, 3205.621, 2851.658, 
    2523.303, 2212.311, 1929.255, 1673.802, 1442.16, 1236.618, 1051.309, 
    900.1193, 761.5495, 642.9122, 540.6172, 453.3608, 379.6924, 317.8554, 
    265.8571, 222.3855, 185.9007, 155.3554, 130.2982, 109.4334, 92.16574, 
    77.78061, 65.77026, 55.71438, 47.28482, 40.32711, 34.41242, 29.41823, 
    25.19542, 21.58195, 18.48265, 15.80275, 13.45813, 11.39787, 9.565165, 
    6.738814, 4.952401, 3.271224, 1.747637, 0.329119, -1.036858, -2.297761 ;
}
```

**Comment by haileyajohnson** [comment] 2023-06-15 17:01
ah my bad, I missed that. Thanks @ethanrd !

**Comment by pedro-cf** [comment] 2023-06-16 09:28
> This is a netCDF-4 file rather than GRIB. So, while similar symptoms, I don't think this is a duplicate of #1060.
> 
> It looks like the `depth` variable isn't a legal "coordinate variable". To be a "coordinate variable", the variable must be strictly monotonic either increasing or decreasing. The `depth` array in this file starts with three values of `4600` (`ncdump -v depth wms_not_working_2023051700.nc`):
> 
> ```
> netcdf wms_not_working_2023051700 {
> ...
> data:
> 
>  depth = **4600, 4600, 4600**, 4334.079, 3956.516, 3577.858, 3205.621, 2851.658, 
>     2523.303, 2212.311, 1929.255, 1673.802, 1442.16, 1236.618, 1051.309, 
>     900.1193, 761.5495, 642.9122, 540.6172, 453.3608, 379.6924, 317.8554, 
>     265.8571, 222.3855, 185.9007, 155.3554, 130.2982, 109.4334, 92.16574, 
>     77.78061, 65.77026, 55.71438, 47.28482, 40.32711, 34.41242, 29.41823, 
>     25.19542, 21.58195, 18.48265, 15.80275, 13.45813, 11.39787, 9.565165, 
>     6.738814, 4.952401, 3.271224, 1.747637, 0.329119, -1.036858, -2.297761 ;
> }
> ```

@haileyajohnson @ethanrd 

Any idea why this same NetCDF's wms access works on this thredds data server v4.6:

http://thredds.maretec.org/thredds/catalog/IST_MOHID_BIO_DATA/TAGUS_0.007DEG_50L_1H/FORECAST/catalog.html?dataset=MOHIDWATERDatasetScan/TAGUS_0.007DEG_50L_1H/FORECAST/2023051700.nc

**Comment by ethanrd** [comment] 2023-06-16 16:32
TDS 4.6 uses ncWMS 1.x while TDS 5.x uses EDAL-Java 2.x (the underpinnings of ncWMS 2.x). The newer software is stricter about a number of requirements on datasets.

**Comment by pedro-cf** [comment] 2023-06-19 09:14
> TDS 4.6 uses ncWMS 1.x while TDS 5.x uses EDAL-Java 2.x (the underpinnings of ncWMS 2.x). The newer software is stricter about a number of requirements on datasets.

would it be possible to change the version of ncWMS ?

**Comment by haileyajohnson** [comment] 2023-06-20 14:13
Unfortunately that is not possible. Your best bet is either to recreate the dataset or edit it virtually with ncml.
